### PR TITLE
Scrolling the list

### PR DESCRIPTION
**Pull request by Ebstein**
the list now scrolls to today.
the cache had a little bug.

### CODE REVIEW

**Comment by jasonkliu** [comment]
From what I understand, `i = 0` is the current month. In your implementation, we have:

``` java
private static final int MONTHS_CACHED_FORWARD = 6;
private static final int MONTHS_CACHED_BACK = 0;
```

so the loop 

``` java
 for (int i = 0; i < MONTHS_CACHED_BACK + MONTHS_CACHED_FORWARD - 1; i++) { ... }
```
actually runs from `i = 0` to `i = 5`, which gives us `i = 0, 1, 2, 3, 4`.
Isn't that only 4 months in the future, instead of 6?

**Comment by Ebstein** [comment]
@jasonkliu yeah, you were right. My bad. There was an error with one of the functions after I listened to the lint comments. Now its ok.

**Comment by Ebstein** [comment]
@jasonkliu @jeminlee @krysjez @abchandra @clhpeterson 

So what do we do about the caching? At the beginning of every month we just wipe the database clean and redownload everything or are we trying to be a bit more sophisticated? Most events are not even planned that early (a month before? I don't think so...). So maybe we should do it once a week? Idk, ideas?

**Comment by jasonkliu** [comment]
r+

**Pull request merged**
